project:
  type: website
  output-dir: docs

website:
  title: "Alexandra Anghel"
  navbar: 
    background: "#E4ADE9"
    title: false
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



